### Import library TensorFlow

In [3]:
import tensorflow as tf
import numpy as np

### Tensor nilai random dengan shape (5,5)

In [4]:
random_tensor = np.around(tf.random.normal([5,5]).numpy(), 2)
random_tensor

array([[-0.79,  0.71, -0.62, -2.4 , -0.18],
       [ 0.09, -0.48,  1.92,  0.63, -0.58],
       [ 1.74, -1.73,  1.59,  0.21, -1.27],
       [ 0.91,  0.89,  0.17,  1.43,  1.46],
       [ 0.62,  0.36,  1.71, -1.92,  2.35]], dtype=float32)

### Tensor dengan shape (5,5) dari list bilangan prima

In [5]:
list = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]

tf.convert_to_tensor(list, dtype=tf.int32)
prime_tensor = tf.reshape(list, (5,5))
prime_tensor

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[ 2,  3,  5,  7, 11],
       [13, 17, 19, 23, 29],
       [31, 37, 41, 43, 47],
       [53, 59, 61, 67, 71],
       [73, 79, 83, 89, 97]])>

### Menampilkan dimensi dari random_tensor dan prime_tensor

In [6]:
print(tf.shape(random_tensor))
print(tf.shape(prime_tensor))

tf.Tensor([5 5], shape=(2,), dtype=int32)
tf.Tensor([5 5], shape=(2,), dtype=int32)


### Perhitungan Aritmetika (Min. 5)

#### Pengurangan

In [7]:
tf.subtract(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[ -2,  -3,  -5,  -9, -11],
       [-13, -17, -18, -23, -29],
       [-30, -38, -40, -43, -48],
       [-53, -59, -61, -66, -70],
       [-73, -79, -82, -90, -95]])>

#### Perkalian

In [8]:
tf.multiply(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[  0,   0,   0, -14,   0],
       [  0,   0,  19,   0,   0],
       [ 31, -37,  41,   0, -47],
       [  0,   0,   0,  67,  71],
       [  0,   0,  83, -89, 194]])>

#### Pembagian

In [9]:
tf.divide(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[ 0.        ,  0.        ,  0.        , -0.28571429,  0.        ],
       [ 0.        ,  0.        ,  0.05263158,  0.        ,  0.        ],
       [ 0.03225806, -0.02702703,  0.02439024,  0.        , -0.0212766 ],
       [ 0.        ,  0.        ,  0.        ,  0.01492537,  0.01408451],
       [ 0.        ,  0.        ,  0.01204819, -0.01123596,  0.02061856]])>

#### Log

In [10]:
tf.math.log(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[        nan, -0.34249035,         nan,         nan,         nan],
       [-2.4079456 ,         nan,  0.65232515, -0.46203548,         nan],
       [ 0.5538851 ,         nan,  0.46373406, -1.5606477 ,         nan],
       [-0.09431066, -0.11653383, -1.7719568 ,  0.35767445,  0.37843648],
       [-0.4780358 , -1.0216513 ,  0.5364934 ,         nan,  0.8544153 ]],
      dtype=float32)>

#### Pangkat

In [11]:
tf.pow(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[   0,    0,    0, -128,    0],
       [   0,    0,    1,    0,    0],
       [   1,   -1,    1,    0,   -1],
       [   0,    0,    0,    1,    1],
       [   0,    0,    1,   -1,    0]])>

### Nilai maksimal dan minimal dari variable random_tensor

In [12]:
tf.argmax(random_tensor, axis=0).numpy()


array([2, 3, 1, 3, 4], dtype=int64)

In [13]:
tf.argmin(random_tensor, axis=0).numpy()

array([0, 2, 0, 0, 2], dtype=int64)

### Concatenation(Penggabungan) dari random_tensor dan prime_tensor

In [14]:
concat = tf.concat([random_tensor, prime_tensor], axis=1)
concat

<tf.Tensor: shape=(5, 10), dtype=int32, numpy=
array([[ 0,  0,  0, -2,  0,  2,  3,  5,  7, 11],
       [ 0,  0,  1,  0,  0, 13, 17, 19, 23, 29],
       [ 1, -1,  1,  0, -1, 31, 37, 41, 43, 47],
       [ 0,  0,  0,  1,  1, 53, 59, 61, 67, 71],
       [ 0,  0,  1, -1,  2, 73, 79, 83, 89, 97]])>

### Descending Sort

In [17]:
dc = tf.sort(random_tensor, direction="DESCENDING")
dc.numpy()

array([[ 0.71, -0.18, -0.62, -0.79, -2.4 ],
       [ 1.92,  0.63,  0.09, -0.48, -0.58],
       [ 1.74,  1.59,  0.21, -1.27, -1.73],
       [ 1.46,  1.43,  0.91,  0.89,  0.17],
       [ 2.35,  1.71,  0.62,  0.36, -1.92]], dtype=float32)

In [18]:
ds = tf.sort(prime_tensor, direction="DESCENDING")
ds.numpy()

array([[11,  7,  5,  3,  2],
       [29, 23, 19, 17, 13],
       [47, 43, 41, 37, 31],
       [71, 67, 61, 59, 53],
       [97, 89, 83, 79, 73]])